name: 'Minify-JS Action'
description: 'Github action to minify html, javascript and css files, using @minify package'

inputs:
  directory:
    description: "File to minify, (By default it minifies in all routes)"
    required: false
  output:
    description: "Path where the minified files will be saved (By default the minified files will be saved in the original file path)"
    required: false

runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: "box"
  color: "green"